In [ ]:
 !git clone -b Exam_Project https://github.com/filipani/Data_Processing_And_Analysis_UniCourse.git

Cloning into 'Data_Processing_And_Analysis_UniCourse'...
remote: Enumerating objects: 42, done.
remote: Counting objects: 100% (42/42), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 42 (delta 6), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (42/42), 1.12 MiB | 7.39 MiB/s, done.
Resolving deltas: 100% (6/6), done.

In [ ]:
import pandas as pd


columns = [
    'class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
    'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
    'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
    'stalk-surface-below-ring', 'stalk-color-above-ring',
    'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
    'ring-type', 'spore-print-color', 'population', 'habitat'
]


path = '/content/Data_Processing_And_Analysis_UniCourse/agaricus-lepiota.data'
df = pd.read_csv(path, names=columns)


df.head()

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-attachment,gill-spacing,gill-size,gill-color,...,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,veil-type,veil-color,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,f,c,n,k,...,s,w,w,p,w,o,p,k,s,u
1,e,x,s,y,t,a,f,c,b,k,...,s,w,w,p,w,o,p,n,n,g
2,e,b,s,w,t,l,f,c,b,n,...,s,w,w,p,w,o,p,n,n,m
3,p,x,y,w,t,p,f,c,n,n,...,s,w,w,p,w,o,p,k,s,u
4,e,x,s,g,f,n,f,w,b,k,...,s,w,w,p,w,o,e,n,a,g

In [ ]:
# Controlliamo quanti '?' ci sono
print(df['stalk-root'].value_counts())

stalk-root
b    3776
?    2480
e    1120
c     556
r     192
Name: count, dtype: int64

In [ ]:
df_reduced = df.drop(columns=['stalk-root'])

In [ ]:

unique_counts = df.nunique()

print("Conteggio valori unici per colonna:")
print(unique_counts)


cols_to_drop = unique_counts[unique_counts == 1].index.tolist()

print(f"\n--- Colonne da rimuovere (Varianza Zero): {cols_to_drop} ---")

Conteggio valori unici per colonna:
class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

--- Colonne da rimuovere (Varianza Zero): ['veil-type'] ---

In [ ]:
import pandas as pd

def check_nzv(data, threshold=0.95):
    nzv_report = []
    for col in data.columns:
        # Calcoliamo la frequenza del valore più comune
        most_freq_ratio = data[col].value_counts(normalize=True).iloc[0]
        # Numero di valori unici
        unique_values = data[col].nunique()

        nzv_report.append({
            'Colonna': col,
            'Frequenza Valore Dominante': f"{most_freq_ratio:.2%}",
            'Valori Unici': unique_values,
            'Is_NZV': most_freq_ratio > threshold
        })

    return pd.DataFrame(nzv_report)

# Eseguiamo l'analisi sul dataset pulito precedentemente
report = check_nzv(df_reduced)
print(report.sort_values(by='Frequenza Valore Dominante', ascending=False))

                     Colonna Frequenza Valore Dominante  Valori Unici  Is_NZV
16                veil-color                     97.54%             4    True
6            gill-attachment                     97.42%             2    True
17               ring-number                     92.17%             3   False
7               gill-spacing                     83.85%             2   False
8                  gill-size                     69.08%             2   False
11  stalk-surface-above-ring                     63.71%             4   False
12  stalk-surface-below-ring                     60.76%             4   False
4                    bruises                     58.44%             2   False
10               stalk-shape                     56.72%             2   False
13    stalk-color-above-ring                     54.95%             9   False
14    stalk-color-below-ring                     53.96%             9   False
0                      class                     51.80%             2   False
20                population                     49.73%             6   False
18                 ring-type                     48.84%             5   False
1                  cap-shape                     45.00%             6   False
5                       odor                     43.43%             9   False
2                cap-surface                     39.93%             4   False
21                   habitat                     38.75%             7   False
19         spore-print-color                     29.39%             9   False
3                  cap-color                     28.11%            10   False
9                 gill-color                     21.27%            12   False
15                 veil-type                    100.00%             1    True

In [ ]:

cols_to_remove = ['veil-type', 'veil-color', 'gill-attachment', 'stalk-root']


df_final = df.drop(columns=cols_to_remove)

print(f"Rimosse {len(cols_to_remove)} colonne.")
print(f"Dataset attuale: {df_final.shape[1]} colonne rimaste.")
print("\nPrime 5 righe del dataset pulito:")
df_final.head()

Rimosse 4 colonne.
Dataset attuale: 19 colonne rimaste.

Prime 5 righe del dataset pulito:

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-spacing,gill-size,gill-color,stalk-shape,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,ring-number,ring-type,spore-print-color,population,habitat
0,p,x,s,n,t,p,c,n,k,e,s,s,w,w,o,p,k,s,u
1,e,x,s,y,t,a,c,b,k,e,s,s,w,w,o,p,n,n,g
2,e,b,s,w,t,l,c,b,n,e,s,s,w,w,o,p,n,n,m
3,p,x,y,w,t,p,c,n,n,e,s,s,w,w,o,p,k,s,u
4,e,x,s,g,f,n,w,b,k,t,s,s,w,w,o,e,n,a,g

In [ ]:
from sklearn.preprocessing import LabelEncoder


df_labeled = df_final.copy()


label_encoders = {}

for col in df_labeled.columns:

    le = LabelEncoder()
    df_labeled[col] = le.fit_transform(df_labeled[col])
    label_encoders[col] = le


print("--- DATASET FATTORIZZATO ---")
display(df_labeled.head())


print("\n" + "="*40)
print("LEGENDE DELLE VARIABILI (Mapping)")
print("="*40)

for col, le in label_encoders.items():

    mapping = dict(zip(le.transform(le.classes_), le.classes_))


    print(f"\n[ {col.upper()} ]")

    for num in sorted(mapping.keys()):
        print(f"  {num} : {mapping[num]}")

print("\n" + "="*40)
print("FINE REPORT")

--- DATASET FATTORIZZATO ---

,class,cap-shape,cap-surface,cap-color,bruises,odor,gill-spacing,gill-size,gill-color,stalk-shape,stalk-surface-above-ring,stalk-surface-below-ring,stalk-color-above-ring,stalk-color-below-ring,ring-number,ring-type,spore-print-color,population,habitat
0,1,5,2,4,1,6,0,1,4,0,2,2,7,7,1,4,2,3,5
1,0,5,2,9,1,0,0,0,4,0,2,2,7,7,1,4,3,2,1
2,0,0,2,8,1,3,0,0,5,0,2,2,7,7,1,4,3,2,3
3,1,5,3,8,1,6,0,1,5,0,2,2,7,7,1,4,2,3,5
4,0,5,2,3,0,5,1,0,4,1,2,2,7,7,1,0,3,0,1

========================================
LEGENDE DELLE VARIABILI (Mapping)
========================================

[ CLASS ]
  0 : e
  1 : p

[ CAP-SHAPE ]
  0 : b
  1 : c
  2 : f
  3 : k
  4 : s
  5 : x

[ CAP-SURFACE ]
  0 : f
  1 : g
  2 : s
  3 : y

[ CAP-COLOR ]
  0 : b
  1 : c
  2 : e
  3 : g
  4 : n
  5 : p
  6 : r
  7 : u
  8 : w
  9 : y

[ BRUISES ]
  0 : f
  1 : t

[ ODOR ]
  0 : a
  1 : c
  2 : f
  3 : l
  4 : m
  5 : n
  6 : p
  7 : s
  8 : y

[ GILL-SPACING ]
  0 : c
  1 : w

[ GILL-SIZE ]
  0 : b
  1 : n

[ GILL-COLOR ]
  0 : b
  1 : e
  2 : g
  3 : h
  4 : k
  5 : n
  6 : o
  7 : p
  8 : r
  9 : u
  10 : w
  11 : y

[ STALK-SHAPE ]
  0 : e
  1 : t

[ STALK-SURFACE-ABOVE-RING ]
  0 : f
  1 : k
  2 : s
  3 : y

[ STALK-SURFACE-BELOW-RING ]
  0 : f
  1 : k
  2 : s
  3 : y

[ STALK-COLOR-ABOVE-RING ]
  0 : b
  1 : c
  2 : e
  3 : g
  4 : n
  5 : o
  6 : p
  7 : w
  8 : y

[ STALK-COLOR-BELOW-RING ]
  0 : b
  1 : c
  2 : e
  3 : g
  4 : n
  5 : o
  6 : p
  7 : w
  8 : y

[ RING-NUMBER ]
  0 : n
  1 : o
  2 : t

[ RING-TYPE ]
  0 : e
  1 : f
  2 : l
  3 : n
  4 : p

[ SPORE-PRINT-COLOR ]
  0 : b
  1 : h
  2 : k
  3 : n
  4 : o
  5 : r
  6 : u
  7 : w
  8 : y

[ POPULATION ]
  0 : a
  1 : c
  2 : n
  3 : s
  4 : v
  5 : y

[ HABITAT ]
  0 : d
  1 : g
  2 : l
  3 : m
  4 : p
  5 : u
  6 : w

========================================
FINE REPORT